### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by agan-tia** [fastly/wafefficacy#23]
When running the standard command, the following error is seen:
```
./run.sh -t https://www.google.com/
Traceback (most recent call last):
  File "/Users/username/Github/wafefficacy/score.py", line 117, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/username/Github/wafefficacy/score.py", line 112, in main
    waf_efficacy = WAFEfficacy(args.filename, args.waf_response, args.precision, args.outfile)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Github/wafefficacy/score.py", line 12, in __init__
    self.results = [json.loads(line) for line in f]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Github/wafefficacy/score.py", line 12, in <listcomp>
    self.results = [json.loads(line) for line in f]
                    ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by skhalsa-sigsci** [comment]
PR https://github.com/fastly/wafefficacy/pull/25 addresses this issue
